name: mc-vanilla
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: 'TRUE'

      # launcher config
      VERSION: '26.1.2'

      # server config
      SERVER_NAME: "E10 Server"
      MOTD: "E10 Server - Hi"
      ICON: /server-utils/e10.png
      OVERRIDE_ICON: true
      DIFFICULTY: 'hard'
      OPS: |
        rllycool
        
      ALLOW_FLIGHT: 'true'
      ENABLE_COMMAND_BLOCK: 'true'
      ENABLE_STATUS: 'true'
      MAX_PLAYERS: '4'

      VIEW_DISTANCE: '32'
      SIMULATION_DISTANCE: '10'
      MEMORY: 12G
      
    volumes:
      # mount file paths
      - ./data:/data
      - ./server-utils:/server-utils
